### ISSUE TITLE
headers not generated before depending packages built

### ISSUE THREAD

**Issue by jonbinney** [ros/genmsg#12]
Only causes problems with make -jN for N greater than 1.

Basically, packages which depend on message packages only depend on the library, not the generated headers, so they might get built before all headers are generated.

@wjwwood 

See make output: https://gist.github.com/4120623

**Comment by dirk-thomas** [comment]
This not a general issue in genmsg. The CMake projects must explicitly state correct dependencies between those targets to guarantee the desired execution order.

Please fill an issue against the affected packages (moveit_msgs or moveit_core?). Based on the log I am just guessing that the library target should depend on the generation of the message for C++ since it tries to include the generated headers. (Besides the target name for generated messages is ${PROJECT_NAME}_gen[cpp|py|lisp|...].

**Comment by jonbinney** [comment]
Makes sense - whereare those targets documented? I don't see it anywhere in the catkin docs, or in any documentation for genmsg. I asked both vincent and william about this and neither of them knew, so other ROS users definitely won't know.

**Comment by wjwwood** [comment]
I didn't know about this.

I think this should go on the wiki, but should it be in the msg/srv
tutorial, the catkin/CMakeLists.txt wiki page or a completely different
wiki page for genmsg specifically?

Should the CMakeLists.txt template make targets depend on std_msgs_gen{cpp,
py}?

## 

On Tue, Nov 20, 2012 at 3:44 PM, jonbinney notifications@github.com wrote:

> Makes sense - whereare those targets documented? I don't see it anywhere
> in the catkin docs, or in any documentation for genmsg. I asked both
> vincent and william about this and neither of them knew, so other ROS users
> definitely won't know.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros/genmsg/issues/12#issuecomment-10579600.

## 

William Woodall
Willow Garage - Software Engineer
wwoodall@willowgarage.com

**Comment by jonbinney** [comment]
The template could have those dependencies, but maybe have them commented out with a comment above them about what they are for.

**Comment by dirk-thomas** [comment]
The genmsg doc is only sparse. It mentions these targets under http://ros.org/doc/api/genmsg/html/usermacros.html
