### ISSUE TITLE
genmsg includes std_msgs even if not find_packaged

### ISSUE THREAD

**Issue by tkruse** [ros/genmsg#17]
Similar steps as for # 16
To reproduce:

``` shell
mkdir genmsg_ws
cd genmsg_ws/
mkdir src
cd src
git clone https://github.com/ros/catkin.git
git clone https://github.com/ros/genmsg.git
catkin_create_pkg foo message_generation roscpp rospy
cd foo
mkdir msg
cd msg
echo "Header header
float32 pressure # [C]
float32 temperature # [kPa]" > bar.msg
cd ..
rm CMakeLists.txt
echo "cmake_minimum_required(VERSION 2.8.3)
project(foo)
find_package(catkin REQUIRED COMPONENTS message_generation roscpp rospy)
add_message_files(
  FILES
  bar.msg
)
generate_messages(
  DEPENDENCIES
  std_msgs  # Or other packages containing msgs
)
catkin_package()" > CMakeLists.txt
cd ../..
. /opt/ros/groovy/setup.bash 
catkin_make
```

works, but should fail since std_msgs was not find_packaged, nor is part of package.xml

**Comment by dirk-thomas** [comment]
generate_messages() depends on the dependencies to have been find_package()-ed before.
If that is not the case it bails out.

In your example std_msgs has been find_package()-ed, since it is a transitive dependency of i.e. roscpp.
So genmsg has no way to figure that out and can therefore not bail out.

find_package(catkin) is on the other hand not called with std_msgs directly and can therefore not bail out about the package.xml.

I.e. the following is perfectly valid CMake code which has no chance of giving the user the feedback you would like to see:

```
find_package(std_msgs)
generate_messages(DEPENDENCIES std_msgs)
```
