### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Interpreter'

### ISSUE THREAD

**Issue by amineHorseman** [ros/genmsg#63]
Hello, 

It seems that both `em` and `empy` build a package with the same name.

When I tried to install RosAria on a fresh install of Kinetic Kame, the following error occured in file `"/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py"`, Line 76:

```
interpreter = em.Interpreter(output=ofile, globals=g, options=em.RAW_OPT:True,em.BUFFERED_OPT:True})
AttributeError: 'module' object has no attribute 'Interpreter
```

I solved this problem by simply uninstalling em, and installing empy:

```
pip uninstall em
pip install empy
```

May be someone should investigate the problem?

**Comment by tfoote** [comment]
As you diagnosed `em` and `empy` are colliding in namespaces. 

https://pypi.python.org/pypi/em
https://pypi.python.org/pypi/EmPy/3.3.2

I'd suggest filing a ticket upstream for em: https://github.com/ikalnitsky/em about the conflict since it appears to be a much smaller and more recent project. 

For our purposes, `empy` is a core upstream dependency we rely upon. It needs to be installed and not the `em` package. If there's any package in the ROS ecosystem depending on `em` please ticket it. But I do not know of any such package.

**Comment by Harsharma2308** [comment]
ddynamic_reconfigure from [realsense_ros](https://github.com/IntelRealSense/realsense-ros) uses em.

**Comment by tfoote** [comment]
For cross reference it's been ticketed on em here: https://github.com/ikalnytskyi/em/issues/9

**Comment by awaisk65** [comment]
> Hello,
> 
> It seems that both `em` and `empy` build a package with the same name.
> 
> When I tried to install RosAria on a fresh install of Kinetic Kame, the following error occured in file `"/opt/ros/kinetic/lib/python2.7/dist-packages/genmsg/template_tools.py"`, Line 76:
> 
> ```
> interpreter = em.Interpreter(output=ofile, globals=g, options=em.RAW_OPT:True,em.BUFFERED_OPT:True})
> AttributeError: 'module' object has no attribute 'Interpreter
> ```
> 
> I solved this problem by simply uninstalling em, and installing empy:
> 
> ```
> pip uninstall em
> pip install empy
> ```
> 
> May be someone should investigate the problem?

pip install empy will install the updated version, which give "em module has  no attribute em.Interpreter". You need to install the downgraded version of empy.
pip install empy==3.3.4

**Comment by kamronkhakimov** [comment]
I have had the same problem. The issue seems to be the em, empy modules. 
Try to use these lines of code:
```
pip uninstall em
pip install empy==3.3.4
```
