### ISSUE TITLE
License clash with em.py?

### ISSUE THREAD

**Issue by ensonic** [ros/genmsg#80]
In https://github.com/ros/genmsg/blob/indigo-devel/src/genmsg/template_tools.py#L39 you import `em`, which I believe is `em.py` from http://www.alcyone.com/software/empy/ and that is LGPL. Your package is marked as BSD (according to http://wiki.ros.org/genmsg).

1.) Please add a LICENSE file to the top of the repo to make this part of the repo.
2.) add em.py to a requirements.txt and list under DEPENDENCIES on (http://wiki.ros.org/genmsg)?

Figure out the license situation -  can you use a different template engine?

Also right now this seems to be only used with c++?
https://github.com/ros/gencpp/blob/indigo-devel/scripts/msg.h.template
Can you confirm?

**Comment by dirk-thomas** [comment]
> In https://github.com/ros/genmsg/blob/indigo-devel/src/genmsg/template_tools.py#L39 you import em, which I believe is em.py from http://www.alcyone.com/software/empy/ and that is LGPL. Your package is marked as BSD (according to http://wiki.ros.org/genmsg).

Yes, do you see a problem with that?

> Please add a LICENSE file to the top of the repo to make this part of the repo.

Many existing ROS 1 repos don't have a `LICENSE` file in the repo. The license is instead stated in the `package.xml` file(s). In this case where only a single package is contained in the repo it should be easy to add a `LICENSE` file. Please consider to create a pull request for it.

> add em.py to a requirements.txt and list under DEPENDENCIES on (http://wiki.ros.org/genmsg)?

ROS 1 packages don't use a `requirements.txt` file even if they contain Python code. The installation is invoked though CMake.

The missing dependency declaration has been addressed in #81. It won't appear under DEPENDENCIES in the wiki page though since that list only enumerates dependencies on other ROS packages.

> Figure out the license situation - can you use a different template engine?

I don't see what needs to be figured out here? Also `em` is being used in numerous places throughout the ROS code base so I don't think replacing it with another engine is going to be feasible.

> Also right now this seems to be only used with c++?
> https://github.com/ros/gencpp/blob/indigo-devel/scripts/msg.h.template
> Can you confirm?

That is certainly one case where `em` templates and the functions provided by this package are being used. I don't think this is the only usage though. But since ROS packages are developed in a federated way there is no way to know for sure.

**Comment by ensonic** [comment]
Thanks for the explanation. I'll leave it up to you to document your dependencies. I also understand that it is hard to read the LGPL from the perspective of python modules which are by nature dynamically loaded. 
So feel free to close the report.
