### ISSUE TITLE
What is the `bar_cpp` referenced by the documentation?

### ISSUE THREAD

**Issue by realtime-neil** [ros/genmsg#82]
Here's a mention of `bar_cpp`:

https://github.com/ros/genmsg/blame/914058a5d3257bd9b2d1d49cb400111effabf875/doc/usermacros.rst#L41

Does it have anything to do with `bar_gencpp`?

https://github.com/ros/genmsg/blame/914058a5d3257bd9b2d1d49cb400111effabf875/doc/usermacros.rst#L39

Is one correct and the other incorrect? If so, which one is correct?

How many languages are supported as targets? Is there a list of these somewhere?

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.

**Comment by dirk-thomas** [comment]
Especially cross posting your question in multiple places (https://answers.ros.org/question/319505/which-languages-and-target-names-does-genmsg-support/) is violating the etiquette.
