### ISSUE TITLE
failed in installing, result “--install-layout not recognized”

### ISSUE THREAD

**Issue by hujianhang2996** [ros/genmsg#87]
when run "sudo make install", result this:
...
...
-- Up-to-date: /usr/local/share/genmsg/cmake/genmsgConfig.cmake
-- Up-to-date: /usr/local/share/genmsg/cmake/genmsgConfig-version.cmake
-- Up-to-date: /usr/local/share/genmsg/package.xml
-- Up-to-date: /usr/local/share/genmsg/cmake/pkg-genmsg.cmake.em
-- Up-to-date: /usr/local/share/genmsg/cmake/pkg-genmsg.context.in
-- Up-to-date: /usr/local/share/genmsg/cmake/pkg-msg-extras.cmake.in
-- Up-to-date: /usr/local/share/genmsg/cmake/pkg-msg-paths.cmake.develspace.in
-- Up-to-date: /usr/local/share/genmsg/cmake/pkg-msg-paths.cmake.installspace.in
+ cd /home/achilles/genmsg
+ mkdir -p /usr/local/lib/python3/dist-packages
+ /usr/bin/env PYTHONPATH=/usr/local/lib/python3/dist-packages:/home/achilles/genmsg/build/lib/python3/dist-packages: CATKIN_BINARY_DIR=/home/achilles/genmsg/build /home/achilles/miniconda3/bin/python /home/achilles/genmsg/setup.py build --build-base /home/achilles/genmsg/build install --install-layout=deb --prefix=/usr/local --install-scripts=/usr/local/bin
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --install-layout not recognized
CMake Error at catkin_generated/safe_execute_install.cmake:4 (message):
  
  execute_process(/home/achilles/genmsg/build/catkin_generated/python_distutils_install.sh)
  returned error code
Call Stack (most recent call first):
  cmake_install.cmake:156 (include)
  

Makefile:61: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
